Disable routes to "reload" using reload_modules(), due to errors.
I happened to run the !!/reload command, which caused my test
instance to lock up. Further testing indicated intermittent results
from complaints from FindSpam:
 TypeError: To match, a rule must have either 'func' or 'regex' valid! : bad keyword in {}
causing a reboot to locking up, and at least some apparent correct
functionality.

I don't have the time to look into this at the moment. Given that
using the routes can cause a lockup, I've just disabled them. In
the cases of the two areas of the code where git changes might have
resulted in a reload_modules(), a full reboot will be performed.

The !!/reload command is just disabled. SD will say the command
doesn't exist.

autopull